##The website title
name: Conti Vivai Lariani
##Markdown processor
markdown: kramdown
##syntax highlighter. change it to pygments
highlighter: rouge

##define base_url for valid usage in sitemap.xml and robots.txt
base_url: http://contivivailariani.github.io
sass:
  sass_dir: _sass
  style: :compressed
#paginate: 5
paginate_path: "page:num"
##The website description (to be used in meta tags)
description: Vivai Lariani di Conti Davide
##Some frequently used keywords on your website
keywords: Conti Davide, vivai, tasso, giardini, lario, lariani

##define this for disqus comment support
#disqus: forumname

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: analyticsDomain

##Some commonly used links
links:
#  facebook: username
#  twitter: username
  email: contivivailariani@gmail.com
  github: contivivailariani

##put desired image in img/ directory and set the value accordingly. If not defined, a placeholder image will be used.
#about_image: placeholder.jpg
##comment this if you want full width posts with no sidebar
sidebar: off
